[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
plugins = pydantic.mypy,sqlalchemy.ext.mypy.plugin

mypy_path = src
explicit_package_bases = true

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-numpy]
ignore_missing_imports = True